### ISSUE TITLE
Fix: functions not found in intercom factory 

### ISSUE THREAD

**Issue by sof9816** [rudderlabs/rudder-integration-intercom-ios#10]
When I install Intercom factory pod, and try to build the app, function not found issue happens for those functions:
```
registerUserWithUserId
registerUnidentifiedUser
updateUser
```
![Screenshot 2024-06-10 at 11 08 11 AM](https://github.com/rudderlabs/rudder-integration-intercom-ios/assets/29151929/164a5381-8561-4c79-8982-63ce145d884f)

**Comment by 1abhishekpandey** [comment]
Hey @sof9816,
It seems you're using v1.0.0 of our integration. Can you please switch to the latest version `1.1.0` and check again?

**Comment by 1abhishekpandey** [comment]
We are closing this issue. If the issue persists, please feel free to reopen it.
